### PR TITLE
Trip planner

### LINKED ISSUE #44: Get data from API in CityFragment

### PR DESCRIPTION
**Pull request by Ivanastimac**
# Overview
Created part of app for planning a trip. Main interface displays parts of trip that has to be planned and if chosen, information that users already chose. Main interface redirects users to specific fragments for choosing, for example country or city, after they click on the button for example "Choose country".

Deals with and closes the following issues: #15, #17, #18, #44, #45, #46, #47, #48

# TO-DO
Connect link on the bottom of every fragment to Explore screen.

### CODE REVIEW

**Review by ivancrg — CHANGES_REQUESTED** [review]
# Requested review

Every feature seems to be working (selection of trip parameters and inserting the trip into the database). However, there are some small problems that I think need to be resolved before marking the milestone as finished.

## Problem 1 - text doesn't fit
While planning a trip, the titles of "Pick destination country" and "Add participants (optional)" screens do not fit in their designated area. I think it should be quick to fix. I attached the photos below.

image

image

## Problem 2 - access without signing in
Access to TripPlannerFragment is possible without logging in using your account. That leads to the possibility of creating a trip and then saving it to a username that doesn't exist (username is probably null).

image


## Problem 3 - selecting date before today possible
As the title says, it is possible to select the days before today as our date of departure.

image

## Problem 4 - navigation drawer "On the go" option
It is possible to click "On the go" navigation link and "Travelling mode" screen shows up and leads us through the process of creating a trip from that point on. From what I understand, removing a line in the navigation drawer's "onNavigationItemSelected" method should solve the problem.

image

## Problem 5 - missing cities
I selected American Samoa as destination country and no cities showed up. I can click next and the app crashes. Could have been a mistake from my part because cities from all other countries that I tested show up properly.

image

## Conclusion
Although 5 problems might seem like a lot, I believe all of them are easy to fix and that fixing will be quick too. Apart from the small issues, everything works perfectly well and the design is well incorporated into the app's visual identity.

**Comment by Ivanastimac** [comment]
# Changes

Changes made in commit abde351:

## Problem 1 - text doesn't fit

Problem was solved by changing layout_height from fixed value to "wrap-content" value of RelativeLayout.

## Problem 2 - access without signing in

Problem was solved by checking if user is logged in before opening expected fragment.

```c
if (LoggedUser.getIsLoggedIn()) {
	getSupportFragmentManager().beginTransaction().replace(R.id.fragment_container, new TripPlannerFragment()).commit();
} else {
	Toast.makeText(this, "You are currently not logged in.", Toast.LENGTH_LONG).show();
	return false;
}
```

## Problem 3 - selecting date before today possible

Problem was solved by adding following line to DateFragment:

```c
datePicker.setMinDate(System.currentTimeMillis() - 1000);
```

## Problem 4 - navigation drawer "On the go" option

Problem was solved by removing unnecessary line from MainActivity.

**Comment by lergahana** [comment]
# Changes

Changes made in 8394de9:

## Problem 5
Problem was solved by updating function public void onResponse(Call call, Response response). 
If the country which is picked is unavailable the error 404 is controlled with the else part of the function which takes the user back to the Country Fragment to pick a different country. The code below shows the solution:

> ```java
> getActivity().runOnUiThread(new Runnable() {
>   public void run() {
>     Toast.makeText(getContext(), "Country not available, please pick another country!", Toast.LENGTH_SHORT).show();
>     FragmentTransaction fragmentTransaction = getActivity()
>        .getSupportFragmentManager().beginTransaction();
>     fragmentTransaction.replace(R.id.fragment_container, new CountryFragment());
>     fragmentTransaction.commit();
>    }
>  });
> ```

The image below shows text that displays in case unavailable country is picked.


country_error

**Review by ivancrg — APPROVED** [review]
# Requested review
Everything works and looks great! I think it can be merged. 😊

**Pull request merged**
